### ISSUE TITLE
Looks like it cannot find module-resolver config if it's in a preset

### ISSUE THREAD

**Issue by aaronjensen** [tleunen/eslint-import-resolver-babel-module#70] opened 2017-10-13 05:15 UTC
We're using a preset for our app that contains our module-resolver config. This resolver appears to only read config if it is directly in the .babelrc. It'd be great if it would walk the entire config, though I'm not sure how challenging that would be.

**Comment by tleunen** [comment] 2017-10-15 01:11
Which version are you using? Could you share your babelrc file? I'd like to try it.
Because we're using babel to know the configuration, so it should see the plugin inside a preset.

**Comment by aaronjensen** [comment] 2017-10-15 01:28
`4.0.0-beta.5`
Our preset isn't public, but something like this should repro it:

`.babelrc`:

```
{
  "presets": [
    "my-preset" 
  ]
}
```

`node_modules/babel-preset-my-preset/index.js`:

```
module.exports = () => ({
  plugins: [
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        alias: {
          '@@foo': 'lodash',
        },
      },
    ],
  ],
})
```

**Comment by Justkant** [comment] 2017-10-16 14:34
I can confirm that the `4.0.0-beta.5` is not working but the `3.0.0` is working with the same config.

---

<details><summary><code>.babelrc</code></summary><p>

```json
{
  "presets": ["react-native"],
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "extensions": [
          ".js",
          ".ios.js",
          ".android.js"
        ]
      }
    ]
  ]
}

```
</p></details>

---


<details><summary><code>.eslintrc.js</code></summary><p>

```javascript
exports.root = true;

exports.plugins = ['prettier'];

exports.extends = [
  'airbnb',
  'prettier',
  'prettier/react',
  'plugin:react-native/all',
];

exports.parser = 'babel-eslint';

exports.env = {
  node: true,
  jest: true,
};

exports.settings = {
  'import/resolver': {
    'babel-module': {
      root: ['./src'],
      extensions: ['.js', '.ios.js', '.android.js'],
    },
  },
  react: {
    version: '16.0',
  },
};

exports.globals = {};

exports.rules = {
  'prettier/prettier': ['error', { trailingComma: 'all', singleQuote: true }],
  // `.jsx` extension cannot be used with React Native
  // https://github.com/airbnb/javascript/issues/982
  'react/jsx-filename-extension': ['error', { extensions: ['.js', '.jsx'] }],
};
```
</p></details>

**Comment by danez** [comment] 2017-10-30 14:34
I have the same problem, just that we use not `require.resolve` but `require` directly.

Seems when trying to find the config this package now requires the plugin to be applied by name. and not with `require.resolve` or `require`

**Comment by tleunen** [comment] 2017-12-11 05:11
Closing since it was fixed in babel-plugin-module-resolver in its version 3.

**Closed by tleunen** 2017-12-11 05:11 UTC
