### ISSUE TITLE
It doesn't seem to work with .babelrc.js

### ISSUE THREAD

**Issue by josepot** [tleunen/eslint-import-resolver-babel-module#62] opened 2017-06-04 00:26 UTC
First of thanks for maintaining this library, I've been using it for a while and I like it a lot.

I'm having an issue that I think that it has to do with the fact that I'm using a `.babelrc.js` file rather than the typical `.babelrc`, the thing is that with the `.babelrc.js` configuration this module doesn't work. Perhaps is because that's a new feature of babel 7?

This are the versions of the relevant libraries that I'm using in my project:
-   "babel-cli": "7.0.0-alpha.9"
-   "babel-core": "7.0.0-alpha.9"
-   "babel-eslint": "^7.2.3"
-   "babel-loader": "^7.0.0"
-   "babel-plugin-module-resolver": "3.0.0-beta.3"
-   "eslint-import-resolver-babel-module": "4.0.0-beta.2"
-   "eslint-plugin-import": "^2.3.0"

**Comment by tleunen** [comment] 2017-10-11 19:33
Thank you @josepot. The issue is already fixed in master. I'll publish a new version soon with the recent changes.

**Closed by tleunen** 2017-10-11 19:33 UTC
