### ISSUE TITLE
Using latest eslint setup shows errors

### ISSUE THREAD

**Issue by roastlechon** [tleunen/eslint-import-resolver-babel-module#30] opened 2016-11-08 05:24 UTC
Dependencies are as follows
```
"eslint-import-resolver-babel-module": "^2.1.1",
"babel-eslint": "^6.1.2",
"eslint": "^3.9.1",
"eslint-config-airbnb": "^13.0.0",
"eslint-plugin-import": "^2.2.0",
"eslint-plugin-jsx-a11y": "^2.2.3",
"eslint-plugin-react": "^6.6.0"
```

.babelrc as follows
```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime",
    "transform-decorators-legacy",
    ["module-resolver", {
      "alias": {
        "src": "./src"
      }
    }]
  ]
}
```

Linting errors are as follows
```
   4:1   error  'src' should be listed in the project's dependencies. Run 'npm i -S src' to add it  import/no-extraneous-dependencies
   4:27  error  Missing file extension for "src/components/App"                     import/extensions
  14:3   error  JSX not allowed in files with extension '.js'                                       react/jsx-filename-extension
```

**Comment by tleunen** [comment] 2016-11-09 02:17
What version of `babel-plugin-module-resolver` are you using, it seems it's missing from your dependency list.

**Comment by vdh** [comment] 2016-11-10 05:20
I'm on `babel-plugin-module-resolver@2.3.0`, but I recently started getting `import/no-extraneous-dependencies` errors when running from a global eslint (`/usr/local/bin/eslint`). The local eslint (`./node_modules/.bin/eslint`) works okay.

**Comment by tleunen** [comment] 2016-11-10 13:21
Are you using the eslint plugin with its version 2.1.1 or 2.2.0? Could you verify if it worked fine with 2.1.1 in your case (which means this would be related to the recent changes to grab the plugin configuration (cc @izaakschroeder) or if we have this issue for a long time?

**Comment by tleunen** [comment] 2016-11-10 14:50
Hmm.. I actually can reproduce the issue with 2.2.0 as well. 2.1.1 is fine.

**Comment by roastlechon** [comment] 2016-11-10 16:23
@tleunen sorry, it is `"babel-plugin-module-resolver": "^2.3.0"`

**Comment by tleunen** [comment] 2016-11-10 16:25
Thanks, but I've found out `babel-plugin-module-resolver` is not the issue. The issue is `eslint-import-resolver-babel-module` v2.2.0 ;)

**Comment by roastlechon** [comment] 2016-11-10 16:26
So if I revert back to `2.1.1` I should be all fine and dandy?

**Comment by tleunen** [comment] 2016-11-10 16:30
It was the case for me.
I'll take a look tonight to see what's wrong with v2.2.0

**Comment by roastlechon** [comment] 2016-11-10 17:10
What combination of versions should I test out? I have...

```
"eslint-import-resolver-babel-module": "^2.1.1",
"babel-plugin-module-resolver": "^2.3.0",
```

**Comment by tleunen** [comment] 2016-11-10 17:12
are you sure you're using 2.1.1? Maybe you have 2.2.0 installed (since it matched what you're asking)

**Comment by roastlechon** [comment] 2016-11-10 17:13
```
➜  my-app-name git:(feature/branch) ✗ cat node_modules/eslint-import-resolver-babel-module/package.json | grep version
    "standard-version": "^3.0.0"
    "release": "standard-version",
  "version": "2.1.1"

```

**Comment by tleunen** [comment] 2016-11-11 00:27
Yes it should work with the 2.1.1 version.

@izaakschroeder This is related to your changes. By default, the cwd should be the path of the babelrc file, not `process.cwd()`. Because cwd in the editor is dirname(file), which is wrong.

**Comment by izaakschroeder** [comment] 2016-11-11 00:51
Got it 👍  will see what I can do tonight 😄

**Comment by tleunen** [comment] 2016-12-19 23:10
Closing due to non activity. Let me know if it's still an issue

**Closed by tleunen** 2016-12-19 23:10 UTC
