### ISSUE TITLE
eslint can't resolve alias paths

### ISSUE THREAD

**Issue by sslotsky** [tleunen/eslint-import-resolver-babel-module#25] opened 2016-08-27 21:18 UTC
I believe I've followed instructions correctly. I have this package as well as `babel-plugin-module-resolver` installed. My .bablrc:

```javascript
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    ["module-resolver", {
      "root": ["./"],
      "alias": {
        "ROOT": "./",
        "APP": "./app",
        "CONFIG": "./config",
        "LIB": "./lib"
      }
    }]
  ]
}
```

The app runs fine so the aliases are working, but I get lots of these warnings when linting:

```
Unable to resolve path to module 'APP/shared/forms'
```

I've tried with an .eslintrc like this:

```javasript
{
  "extends": "airbnb",
  "parser": "babel-eslint",
  "plugins": ["react"],
  "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
  "rules": {
    "new-cap": [2, { "capIsNewExceptions": ["List", "Map"] }],
    "semi": [2, "never"],
    "comma-dangle": [2, "never"],
    "no-constant-condition": ["off"],
    "import/no-extraneous-dependencies": ["off"]
  }
}
```

and with an .eslintrc.yml like this

```
extends: airbnb
parser: 'babel-eslint'
plugins:
  - react
import/resolver: 'babel-module'
rules:
  new-cap:
    - 2
    - capIsNewExceptions:
      - List
      - Map
  semi:
    - 2
    - never
  comma-dangle:
    - 2
    - never
  no-constant-condition:
    - off
  import/no-extraneous-dependencies:
    - off
```

Makes no difference. Surely I've missed something?

**Comment by sslotsky** [comment] 2016-08-27 22:04
**Update**

After removing this

```
"import/no-extraneous-dependencies": ["off"]
```

most of my aliases are passing lint, but the `APP` alias now fails `import/no-extraneous-dependencies`

**Comment by tleunen** [comment] 2016-08-27 22:22
How do you run your linting, from where? Editor or CLI? From the root project?

I don't have the issue in my projects, so if you can reproduce the issue in a small example, it could also help.

**Comment by sslotsky** [comment] 2016-08-28 05:47
If you checkout the `lint` branch and run `npm run lint` from the root, you'll see the errors.

https://github.com/sslotsky/brewtoad-react-client/tree/lint

 What's interesting is that the `APP` alias is referenced from `app/users/New` and the linter doesn't complain about it at all, but apparently the ones in `app/recipes/Index` are different?

**Comment by tleunen** [comment] 2016-08-28 15:27
Thanks for the repo, I've been able to reproduce the issue.
Because you're using the jsx extension, you have to manually specify it to the eslint plugin, by using this:
```json
"import/resolver": {
  "babel-module": {
    "extensions": [".js", ".jsx"]
    }
}
```

Also, it seems the root and alias configuration are in conflict with your setup. I believe this is a case sensitivity issue but I still have to investigate a bit more.

**Comment by tleunen** [comment] 2016-08-28 15:35
Yes this is a case sensitivity issue.

You have imports like `CONFIG/locales`, and at the same time, you have a root configuration as `./` and you have a directory called `config` at the rot of your project.

So the system found the file under the directory using the root configuration, and because of that it keeps the `CONFIG/locales` path you were using. The file was found, even if the case doesn't match because of the OS. (MacOS is not case sensitive by default).

So I would remove the root configuration in your case, or the alias (but if you remove the alias, you'd need to update your paths to use `config/locales` instead of `CONFIG/locales` for example).

I'm closing this ticket because it's not an issue with the eslint-import resolver.

**Closed by tleunen** 2016-08-28 15:35 UTC

**Comment by sslotsky** [comment] 2016-08-28 15:40
Thanks for looking into it!

**Comment by Misiur** [comment] 2017-08-07 16:53
I'd suggest putting https://github.com/tleunen/eslint-import-resolver-babel-module/issues/25#issuecomment-242980792 in readme, because I just lost a few hours not knowing it won't find `.jsx` files
